rabbitMQ:
  host: armadillo.rmq.cloudamqp.com
  port: 5672
  user: mnvczwsy
  password: bijdXySzgcZ19kd-EthlzcCCLpYgU1a-
  vhost: /mnvczwsy
  exchange: exchange
  queue: queue
  routingKey: routingKey
logger:
  level: debug
echo:
  port: ":5002"
  timeout: 30
  basePath: /api/v1
  host: "http://localhost"
postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbName: noti_postgres
  sslMode: false
